version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./Internals:/app/Internals 
    environment:
      - GO_ENV=development

networks:
  default:
    driver: bridge
